/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.Interfaz.IControladorEspectaculo;
import Logica.Fabrica;
import static Presentacion.AltaEspectaculo.jFrameBuscarArtista;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Presentacion.MenuInicio;
//import Presentacion.MenuInicio.jDesktopPane2;
import static Presentacion.MenuInicio.jDesktopPane2;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Admin
 */
public class AltaEspectaculo extends javax.swing.JInternalFrame {

    private IControladorEspectaculo ICE;
    /**
     * Creates new form AltaEspectaculo
     */
    public AltaEspectaculo() {
        
        initComponents();
        this.ICE = Fabrica.getInstance().getIControladorEspectaculo();
        this.ICE.obtenerPlataformasToComboBox(jComboBox1Plataformas);
        //this.ICE.obtenerPlataformas();
        this.ICE.obtenerArtistas();
        //jComboBox1= this.ICE.obtenerPlataformas();
        //jComboBox1.addItem(this.ICE.obtenerPlataformas().getItemAt(0).toString());
//        jLabelErrorCantidadEspectadorMaxima1.setText("");
//        jLabelErrorCantidadEspectadorMinima.setText("");
        controlCamposVacios();
        jLabelErrorCase.setForeground(Color.BLACK);
        jLabelDescripcionTam.setVisible(false);
//        jLabelErrorHoras.setText("");
//        jLabelErrorMinutos.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameBuscarArtista = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListArtistas = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jFrameModificar = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtNombreArtista = new javax.swing.JTextField();
        txtCantidadMaxima = new javax.swing.JTextField();
        txtNombreEspectaculo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        txtCantidadMinima = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMinutos = new javax.swing.JTextField();
        txtURL = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jComboBox1Plataformas = new javax.swing.JComboBox<>();
        jLabelDescripcionTam = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        jLabelErrorCase = new javax.swing.JLabel();

        jFrameBuscarArtista.setMinimumSize(new java.awt.Dimension(340, 330));
        jFrameBuscarArtista.setResizable(false);
        jFrameBuscarArtista.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setMaximumSize(new java.awt.Dimension(320, 370));
        jPanel2.setMinimumSize(new java.awt.Dimension(320, 370));
        jPanel2.setPreferredSize(new java.awt.Dimension(320, 370));

        jTextField1.setText("Filtrar por nick");
        jTextField1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField1CaretUpdate(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jScrollPane2.setViewportView(jListArtistas);

        jButton2.setText("Seleccionar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(94, 94, 94))
        );

        jFrameBuscarArtista.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 330, 280));

        jFrameModificar.setMinimumSize(new java.awt.Dimension(516, 266));
        jFrameModificar.setResizable(false);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("ERROR: Ha ocurrido un problema al momento intentar crear el espectáculo.\nDETALLES: El problema se ha presentado debido a que el nombre del\nespectáculo ingresado ya existe en el sistema.\nSUGERENCIA: Modifique el nombre del espectáculo e intente nuevamente.\nADVERTENCIA: Si pulsa 'Cancelar' se perderán todos los datos ingresados.");
        jScrollPane3.setViewportView(jTextArea1);

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel12.setText("¿Desea modificar el nombre del espectáculo?");

        jButton4.setText("Modificar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrameModificarLayout = new javax.swing.GroupLayout(jFrameModificar.getContentPane());
        jFrameModificar.getContentPane().setLayout(jFrameModificarLayout);
        jFrameModificarLayout.setHorizontalGroup(
            jFrameModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameModificarLayout.createSequentialGroup()
                .addGroup(jFrameModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrameModificarLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrameModificarLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addGroup(jFrameModificarLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel12)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jFrameModificarLayout.setVerticalGroup(
            jFrameModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameModificarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jFrameModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton4))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Alta de Espectáculo");
        setMaximumSize(new java.awt.Dimension(540, 540));
        setMinimumSize(new java.awt.Dimension(540, 540));
        setPreferredSize(new java.awt.Dimension(540, 540));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        txtNombreArtista.setEditable(false);
        txtNombreArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreArtistaActionPerformed(evt);
            }
        });
        txtNombreArtista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreArtistaKeyPressed(evt);
            }
        });

        txtCantidadMaxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadMaximaActionPerformed(evt);
            }
        });
        txtCantidadMaxima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadMaximaKeyPressed(evt);
            }
        });

        txtNombreEspectaculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEspectaculoActionPerformed(evt);
            }
        });
        txtNombreEspectaculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreEspectaculoKeyPressed(evt);
            }
        });

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtDescripcion);

        txtCantidadMinima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadMinimaActionPerformed(evt);
            }
        });
        txtCantidadMinima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadMinimaKeyPressed(evt);
            }
        });

        jLabel1.setText("Nickname del organizador");

        jLabel2.setText("Nombre del espectáculo");

        jLabel3.setText("Descripción");

        txtMinutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinutosActionPerformed(evt);
            }
        });
        txtMinutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMinutosKeyPressed(evt);
            }
        });

        txtURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtURLActionPerformed(evt);
            }
        });
        txtURL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtURLKeyPressed(evt);
            }
        });

        jLabel4.setText("Duración del espectáculo(Minutos)");

        jLabel5.setText("Cantidad de espectadores:");

        txtCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoActionPerformed(evt);
            }
        });
        txtCosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCostoKeyPressed(evt);
            }
        });

        jLabel6.setText("Mínima");

        jLabel10.setText("Plataforma");

        jLabel7.setText("Máxima");

        jLabel8.setText("URL");

        jLabel9.setText("Costo $");

        jButton3.setText("Seleccioanr");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox1Plataformas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1PlataformasActionPerformed(evt);
            }
        });

        jLabelDescripcionTam.setText("jLabel11");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNombreArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3))
                            .addComponent(jComboBox1Plataformas, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreEspectaculo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidadMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidadMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(64, 64, 64)
                        .addComponent(jLabelDescripcionTam))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 45, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox1Plataformas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreEspectaculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelDescripcionTam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txtCantidadMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtCantidadMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        jLabelErrorCase.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabelErrorCase.setText("Este label será utilizado para informar de errores mediante Try-Catchs");
        jLabelErrorCase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabelErrorCaseKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelErrorCase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirmar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelErrorCase)
                    .addComponent(btnConfirmar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreEspectaculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEspectaculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEspectaculoActionPerformed

    private void txtNombreArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreArtistaActionPerformed

    private void txtCantidadMinimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadMinimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadMinimaActionPerformed

    private void txtURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtURLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtURLActionPerformed

    private void txtCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoActionPerformed

    private void txtCantidadMaximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadMaximaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadMaximaActionPerformed

    private void txtCantidadMinimaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadMinimaKeyPressed
         try{
            int i=Integer.parseInt(txtCantidadMinima.getText());
            jLabelErrorCase.setText("");
            controlCamposVacios();
        }catch(NumberFormatException e){
            jLabelErrorCase.setText("ERROR: El número que digitó en el campo 'Cantidad de espectadores mínimos' es inválido.");
            jLabelErrorCase.setForeground(Color.RED);
            btnConfirmar.setEnabled(false);
        }
    }//GEN-LAST:event_txtCantidadMinimaKeyPressed

    private void jLabelErrorCaseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabelErrorCaseKeyPressed

    }//GEN-LAST:event_jLabelErrorCaseKeyPressed

    private void txtCantidadMaximaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadMaximaKeyPressed
         try{
            int i=Integer.parseInt(txtCantidadMaxima.getText());
            jLabelErrorCase.setText("");
            controlCamposVacios();
        }catch(NumberFormatException e){
            jLabelErrorCase.setText("ERROR: El número que digitó en el campo 'Cantidad de espectadores máximos' es inválido.");
            jLabelErrorCase.setForeground(Color.RED);
            btnConfirmar.setEnabled(false);
        }
    }//GEN-LAST:event_txtCantidadMaximaKeyPressed

    private void txtMinutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinutosActionPerformed

    private void txtMinutosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMinutosKeyPressed
         try{
            double i=Double.parseDouble(txtMinutos.getText());
             jLabelErrorCase.setText("");
            controlCamposVacios();   
        }catch(NumberFormatException e){
            jLabelErrorCase.setText("ERROR: El número que digitó en el campo 'Minutos' es inválido.");
            jLabelErrorCase.setForeground(Color.RED);
            btnConfirmar.setEnabled(false);
        }
    }//GEN-LAST:event_txtMinutosKeyPressed

    private void txtCostoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostoKeyPressed
        try{
            double i=Double.parseDouble(txtCosto.getText());
            controlCamposVacios();
        }catch(NumberFormatException e){
            jLabelErrorCase.setText("ERROR: El número que digitó en el campo 'Costo' es inválido.");
            jLabelErrorCase.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtCostoKeyPressed

//    public static class JOptionPaneTest2 {
//
//        public static void main() {
//            JDialog.setDefaultLookAndFeelDecorated(true);
//            int response = JOptionPane.showConfirmDialog(null, "Nombre del espectáculo ya existe en el sistema. ¿Desea modificar el nombre?", "Confirm",
//                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
//            if (response == JOptionPane.NO_OPTION) {
//                this.
//                System.out.println("No button clicked");
//            } else if (response == JOptionPane.YES_OPTION) {
//                
//                System.out.println("Yes button clicked");
//            } else if (response == JOptionPane.CLOSED_OPTION) {
//                System.out.println("JOptionPane closed");
//            }
//        }
//    }
    
    
    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if (txtURL.getText().matches("^(https?|ftp|file)://[-a-zA-Z0-9+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9+&@#/%=~_|]")){ // Expresion regular para comprobar la url
            String nombrePlataforma= jComboBox1Plataformas.getSelectedItem().toString();
            String nombreOrganizador= txtNombreArtista.getText();
            String nombreEspectaculo= txtNombreEspectaculo.getText();
            String descripcion = txtDescripcion.getText();
            Double duracion= Double.parseDouble(txtMinutos.getText());
            int cantEspectadoresMinima = Integer.parseInt(txtCantidadMinima.getText());
            int cantEspectadoresMaxima = Integer.parseInt(txtCantidadMaxima.getText());
            String URL = txtURL.getText();
            Double Costo = Double.parseDouble(txtCosto.getText());
            if(controlCamposCorrectos()==0){ //EN CASO DE QUE TODOS LOS DATOS INGRESADOS SEAN COHERENTES/CORRECTO SE PROCEDE A CARGAR LOS DATOS A LA DB
                if (this.ICE.verificarNombreEspectaculo(nombreEspectaculo)==true) { //EN CASO DE QUE EL NOMBRE INGRESADO DE ESPECTÁCULO EXISTA SE PROCEDE CON LA OPCION DE MODIFICAR O CANCELAR EL CASO DE USO
                    Dimension desktopSize = jDesktopPane2.getSize();
                    Dimension jInternalFrameSize = jFrameModificar.getSize();
                    jFrameModificar.setLocation((jDesktopPane2.getWidth() - jInternalFrameSize.width)/2,
                    (jDesktopPane2.getHeight() - jInternalFrameSize.height)/2);
                    jFrameModificar.setVisible(true);
                }else{
                    this.ICE.altaEspectaculo(nombrePlataforma, nombreOrganizador, nombreEspectaculo, descripcion, duracion, cantEspectadoresMinima, cantEspectadoresMaxima, URL, Costo);
                    JOptionPane.showMessageDialog(this, "Espectáculo agregado exitosamente.");
                    this.dispose();
                }
            }else{
                controlCamposVacios();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Link Web no valido");
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        
    }//GEN-LAST:event_formMouseMoved

    private void txtNombreArtistaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreArtistaKeyPressed
        controlCamposVacios(); 
    }//GEN-LAST:event_txtNombreArtistaKeyPressed

    private void txtNombreEspectaculoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreEspectaculoKeyPressed
        controlCamposVacios();
    }//GEN-LAST:event_txtNombreEspectaculoKeyPressed

    private void txtDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyPressed
        if(txtDescripcion.getText().length()+1>255){
            btnConfirmar.setEnabled(false);
            jLabelDescripcionTam.setForeground(Color.RED);
        }
        else{
            int i=txtDescripcion.getText().length()+1;
            String iString= Integer.toString(i);
            jLabelDescripcionTam.setText(iString + "/255");
            btnConfirmar.setEnabled(true);
            jLabelDescripcionTam.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtDescripcionKeyPressed

    private void txtURLKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtURLKeyPressed
        controlCamposVacios();
    }//GEN-LAST:event_txtURLKeyPressed

    private void jComboBox1PlataformasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1PlataformasActionPerformed
     
    }//GEN-LAST:event_jComboBox1PlataformasActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Dimension desktopSize = jDesktopPane2.getSize();
        Dimension jInternalFrameSize = jFrameBuscarArtista.getSize();
        jFrameBuscarArtista.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
        (desktopSize.height- jInternalFrameSize.height)/2);
        jFrameBuscarArtista.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(jListArtistas.isSelectionEmpty()){
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningun artista.");
        }else{
            txtNombreArtista.setText(jListArtistas.getSelectedValue());
            jFrameBuscarArtista.setVisible(false);
            controlCamposVacios();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jFrameModificar.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jFrameModificar.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
//        try{
//           this.ICE.obtenerArtistaPorNombre(jTextField1.getText());
//        }catch (java.lang.Exception e){ //SI INGRESA SOLO ESPACIOS LE SALE UNA ADVERTENCIA Y SE REINICIA EL JTEXTFIELD.
//            jTextField1.enable(false);
//            JOptionPane.showMessageDialog(null, "No puede ingresar solo espaciados, debe ingresar al menos una letra.", "ERROR:", JOptionPane.ERROR_MESSAGE);
//            jTextField1.enable(true);
//            jTextField1.setText("");
//            this.ICE.obtenerArtistaPorNombre(jTextField1.getText());
//        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField1CaretUpdate
        // TODO add your handling code here:
        this.ICE.obtenerArtistaPorNick(jTextField1.getText());
    }//GEN-LAST:event_jTextField1CaretUpdate

    public void controlCamposVacios(){
        if(txtCantidadMaxima.getText().equalsIgnoreCase("") || txtCantidadMinima.getText().equalsIgnoreCase("") || txtCosto.getText().equalsIgnoreCase("") || txtDescripcion.getText().equalsIgnoreCase("") || txtDescripcion.getText().equalsIgnoreCase("") || txtMinutos.getText().equalsIgnoreCase("") || txtNombreArtista.getText().equalsIgnoreCase("") || txtNombreEspectaculo.getText().equalsIgnoreCase("") || txtURL.getText().equalsIgnoreCase("")){
            jLabelErrorCase.setText("ADVERTENCIA: Se requiere completar todos los campos para confirmar.");
            jLabelErrorCase.setForeground(Color.BLACK);
            btnConfirmar.setEnabled(false);
        }
        else {
            if(controlCamposCorrectos()==0){
                jLabelErrorCase.setText("");
                jLabelErrorCase.setForeground(Color.BLACK);
                btnConfirmar.setEnabled(true);
            }else if(controlCamposCorrectos()==1){
                jLabelErrorCase.setText("ERROR: Uno de los campos no es correcto, verifique.");
                jLabelErrorCase.setForeground(Color.RED);
            }
            else if(controlCamposCorrectos()==-1){
                jLabelErrorCase.setText("ERROR: No puede establecer valores negativos en el campo 'Minutos'.");
                jLabelErrorCase.setForeground(Color.RED);
            }
            else if(controlCamposCorrectos()==-11){
                jLabelErrorCase.setText("ERROR: El campo 'Minutos' no puede ser cero.");
                jLabelErrorCase.setForeground(Color.RED);
            }
            else if(controlCamposCorrectos()==-2){
                jLabelErrorCase.setText("ERROR: No puede establecer valores negativos en el campo 'Máxima'.");
                jLabelErrorCase.setForeground(Color.RED);
            }
            else if(controlCamposCorrectos()==-3){
                jLabelErrorCase.setText("ERROR: No puede establecer valores negativos en el campo 'Mínima'.");
                jLabelErrorCase.setForeground(Color.RED);
            }
            else if(controlCamposCorrectos()==-4){
                jLabelErrorCase.setText("ERROR: El campo 'Maxima' no puede ser menor que 'Mínima'.");
                jLabelErrorCase.setForeground(Color.RED);
            }
            else if(controlCamposCorrectos()==-5){
                jLabelErrorCase.setText("ERROR: No puede establecer valores negativos en el campo 'Costo'.");
                jLabelErrorCase.setForeground(Color.RED);
            }
        }
    }
    
    public int controlCamposCorrectos() {
        int cont = 0;
        try {
            double i = Double.parseDouble(txtCosto.getText());
            if(i<0){
                return -5;
            }
        } catch (NumberFormatException e) {
            cont++;
        }
        try {
            int i = Integer.parseInt(txtMinutos.getText());
            if(i<0){
                return -1;
            }
            if(i==0){
                return -11;
            }
        } catch (NumberFormatException e) {
            cont++;
        }
        try {
            int i = Integer.parseInt(txtCantidadMaxima.getText());
            if(i<0){
                return -2;
            }
        } catch (NumberFormatException e) {
            cont++;
        }
        try {
            int i = Integer.parseInt(txtCantidadMinima.getText());
             if(i<0){
                return -3;
            }
        } catch (NumberFormatException e) {
            cont++;
        }
        try {
            int min = Integer.parseInt(txtCantidadMinima.getText());
            int max = Integer.parseInt(txtCantidadMaxima.getText());
             if(max<min){
                return -4;
            }
        } catch (NumberFormatException e) {
            cont++;
        }
        if(cont==0){
            return 0;
        }
        else{
            return 1;
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnConfirmar;
    public static javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton3;
    public static javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    public static javax.swing.JComboBox<String> jComboBox1Plataformas;
    public static javax.swing.JFrame jFrameBuscarArtista;
    public static javax.swing.JFrame jFrameModificar;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel jLabelDescripcionTam;
    public static javax.swing.JLabel jLabelErrorCase;
    public static javax.swing.JList<String> jListArtistas;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextField jTextField1;
    public static javax.swing.JTextField txtCantidadMaxima;
    public static javax.swing.JTextField txtCantidadMinima;
    public static javax.swing.JTextField txtCosto;
    public static javax.swing.JTextArea txtDescripcion;
    public static javax.swing.JTextField txtMinutos;
    public static javax.swing.JTextField txtNombreArtista;
    public static javax.swing.JTextField txtNombreEspectaculo;
    public static javax.swing.JTextField txtURL;
    // End of variables declaration//GEN-END:variables
}
