/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.Fabrica;
import Logica.Interfaz.IControladorEspectaculo;
import Logica.Interfaz.IControladorPaquete;
import static Presentacion.MenuInicio.jDesktopPane2;
import java.awt.Dimension;
import java.io.Console;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class ConsultaEspectaculo extends javax.swing.JInternalFrame {

    private IControladorEspectaculo ICE;
    private IControladorPaquete ICP;
    
    public ConsultaEspectaculo() {
        initComponents();
        setLabelsTxtNotVisible();
        this.ICE = Fabrica.getInstance().getIControladorEspectaculo();
        this.ICP = Fabrica.getInstance().getIControladorPaquete();
        this.ICE.obtenerPlataformas(this.listPlataformas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollPane6 = new javax.swing.JScrollPane();
        listPlataformas = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listEspectaculos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        btnSelecionar = new javax.swing.JButton();
        txtNombreArtista = new javax.swing.JLabel();
        txtNombreEspectaculo = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JLabel();
        txtCantEspectadoresMinima = new javax.swing.JLabel();
        txtCantEspectadoresMaxima = new javax.swing.JLabel();
        txtURL = new javax.swing.JLabel();
        txtCosto = new javax.swing.JLabel();
        txtFechaRegistro = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listFunciones = new javax.swing.JList<>();
        btnFuncion = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listPaquetes = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        btnFuncion1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelNombreFP = new javax.swing.JLabel();
        labelDescripcionP_FechaF = new javax.swing.JLabel();
        labelFechaInicioP_HoraInicioF = new javax.swing.JLabel();
        labelFechaFinP_FechaRegistroF = new javax.swing.JLabel();
        labelCostoP = new javax.swing.JLabel();
        labelDescuentoP = new javax.swing.JLabel();
        txtNombreFP = new javax.swing.JLabel();
        txtDescripcionP_FechaF = new javax.swing.JLabel();
        txtFechaInicioP_HoraInicioF = new javax.swing.JLabel();
        txtFechaFinP_FechaRegistroF = new javax.swing.JLabel();
        txtCostoP = new javax.swing.JLabel();
        txtDescuentoP = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelPaqueteEspectaculos = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listEspectaculosDePaquete = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        jFrame1.setTitle("Seleccionar plataformas");
        jFrame1.setMinimumSize(new java.awt.Dimension(370, 190));
        jFrame1.setResizable(false);

        listPlataformas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Facebook Live", "Amazon live premiun 4k", "test", "Item 4", "Item 5", "test2", "test3", "test4", "asd" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(listPlataformas);

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        setClosable(true);
        setTitle("Consultar espectáculo");
        setMaximumSize(new java.awt.Dimension(740, 630));
        setMinimumSize(new java.awt.Dimension(740, 630));
        setPreferredSize(new java.awt.Dimension(740, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setViewportView(listEspectaculos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 250, 88));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setText("Artista organizador:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setText("Nombre del espectáculo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel4.setText("Duración en minutos:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel5.setText("Cantidad de espectadores mínima:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel6.setText("Cantidad de espectadores máxima:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel7.setText("URL:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel8.setText("Costo:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel9.setText("Fecha de registro:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        txtDescripcion.setEditable(false);
        txtDescripcion.setColumns(20);
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 250, -1));

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel10.setText("Espectáculos:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        btnSelecionar.setText("Seleccionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelecionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));
        getContentPane().add(txtNombreArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));
        getContentPane().add(txtNombreEspectaculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));
        getContentPane().add(txtDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));
        getContentPane().add(txtCantEspectadoresMinima, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));
        getContentPane().add(txtCantEspectadoresMaxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, -1));
        getContentPane().add(txtURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));
        getContentPane().add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));
        getContentPane().add(txtFechaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, -1));

        jScrollPane3.setViewportView(listFunciones);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 250, 66));

        btnFuncion.setText("Seleccionar");
        btnFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionActionPerformed(evt);
            }
        });
        getContentPane().add(btnFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, -1));

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel11.setText("Funciones:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jScrollPane4.setViewportView(listPaquetes);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 250, 66));

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel12.setText("Paquetes:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        btnFuncion1.setText("Seleccionar");
        btnFuncion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncion1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnFuncion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, -1, -1));

        labelNombreFP.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        labelNombreFP.setText("Nombre de función:");

        labelDescripcionP_FechaF.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        labelDescripcionP_FechaF.setText("labelDescripcionP_FechaF");

        labelFechaInicioP_HoraInicioF.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        labelFechaInicioP_HoraInicioF.setText("labelFechaInicioP_HoraInicioF");

        labelFechaFinP_FechaRegistroF.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        labelFechaFinP_FechaRegistroF.setText("labelFechaFinP_FechaRegistroF");

        labelCostoP.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        labelCostoP.setText("labelCostoP");

        labelDescuentoP.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        labelDescuentoP.setText("labelDescuentoP");

        txtNombreFP.setText("txtNombreFP");

        txtDescripcionP_FechaF.setText("Variable2");

        txtFechaInicioP_HoraInicioF.setText("Variable3");

        txtFechaFinP_FechaRegistroF.setText("Variable4");

        txtCostoP.setText("Variable5");

        txtDescuentoP.setText("Variable6");

        labelPaqueteEspectaculos.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        labelPaqueteEspectaculos.setText("Espectáculos que ofrece el paquete:");

        listEspectaculosDePaquete.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(listEspectaculosDePaquete);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPaqueteEspectaculos)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPaqueteEspectaculos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelDescuentoP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDescuentoP))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelDescripcionP_FechaF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescripcionP_FechaF))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelNombreFP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreFP))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelFechaInicioP_HoraInicioF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaInicioP_HoraInicioF))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelFechaFinP_FechaRegistroF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaFinP_FechaRegistroF))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelCostoP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCostoP))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreFP)
                    .addComponent(txtNombreFP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDescripcionP_FechaF)
                    .addComponent(txtDescripcionP_FechaF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFechaInicioP_HoraInicioF)
                    .addComponent(txtFechaInicioP_HoraInicioF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFechaFinP_FechaRegistroF)
                    .addComponent(txtFechaFinP_FechaRegistroF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCostoP)
                    .addComponent(txtCostoP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDescuentoP)
                    .addComponent(txtDescuentoP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        jButton2.setText("Plataforma");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 260, -1));

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel13.setText("Descripción del espectáculo:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionActionPerformed
        if (listFunciones.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ninguna función.");
        }else{
            this.ICE.cargarDatosFuncionConsultaEspectaculo(listFunciones.getSelectedValue(),txtNombreFP,txtDescripcionP_FechaF, txtFechaInicioP_HoraInicioF, txtFechaFinP_FechaRegistroF);
            labelNombreFP.setText("Nombre de función:");
            labelDescripcionP_FechaF.setText("Fecha de función:");
            labelFechaInicioP_HoraInicioF.setText("Hora de inicio:");
            labelFechaFinP_FechaRegistroF.setText("Fecha de registro:");

            labelNombreFP.setVisible(true);
            labelDescripcionP_FechaF.setVisible(true);
            labelFechaInicioP_HoraInicioF.setVisible(true);
            labelFechaFinP_FechaRegistroF.setVisible(true);
            txtNombreFP.setVisible(true);
            txtDescripcionP_FechaF.setVisible(true);
            txtFechaInicioP_HoraInicioF.setVisible(true);
            txtFechaFinP_FechaRegistroF.setVisible(true);

            labelDescuentoP.setVisible(false);
            labelCostoP.setVisible(false);
            txtDescuentoP.setVisible(false);
            txtCostoP.setVisible(false);
            
            jPanel2.setVisible(false);
        }

    }//GEN-LAST:event_btnFuncionActionPerformed

    private void btnFuncion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncion1ActionPerformed
        if(listPaquetes.isSelectionEmpty()){
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningún paquete.");
        }else{
            this.ICE.cargarDatosPaqueteConsultaEspectaculo(txtNombreEspectaculo.getText(), listPaquetes.getSelectedValue(),txtNombreFP,txtDescripcionP_FechaF, txtFechaInicioP_HoraInicioF, txtFechaFinP_FechaRegistroF, txtCostoP, txtDescuentoP, listEspectaculosDePaquete);
            labelNombreFP.setText("Nombre del paquete:");
            labelDescripcionP_FechaF.setText("Descripción:");
            labelFechaInicioP_HoraInicioF.setText("Fecha de inicio:");
            labelFechaFinP_FechaRegistroF.setText("Fecha de fin:");
            labelCostoP.setText("Costo: $");
            labelDescuentoP.setText("Descuento: %");
            
            labelNombreFP.setVisible(true);
            labelDescripcionP_FechaF.setVisible(true);
            labelFechaInicioP_HoraInicioF.setVisible(true);
            labelFechaFinP_FechaRegistroF.setVisible(true);
            labelDescuentoP.setVisible(true);
            labelCostoP.setVisible(true);
            txtNombreFP.setVisible(true);
            txtDescripcionP_FechaF.setVisible(true);
            txtFechaInicioP_HoraInicioF.setVisible(true);
            txtFechaFinP_FechaRegistroF.setVisible(true);
            txtDescuentoP.setVisible(true);
            txtCostoP.setVisible(true);
            jPanel2.setVisible(true);
//            labelPaqueteEspectaculos.setVisible(true);
//            listEspectaculosDePaquete.setVisible(true);
        }
    }//GEN-LAST:event_btnFuncion1ActionPerformed

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        if (jTextField1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ninguna plataforma.");
        } else if (listEspectaculos.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningun espectaculo.");
        }
        else{//JLabel nombreApellido, JLabel nombreEspectaculo, JLabel duracion, JLabel espectMin, JLabel espectMax, JLabel URL, JLabel costo, JLabel fecha, JTextArea descrip);
                        labelNombreFP.setVisible(false);
            labelDescripcionP_FechaF.setVisible(false);
            labelFechaInicioP_HoraInicioF.setVisible(false);
            labelFechaFinP_FechaRegistroF.setVisible(false);
            txtNombreFP.setVisible(false);
            txtDescripcionP_FechaF.setVisible(false);
            txtFechaInicioP_HoraInicioF.setVisible(false);
            txtFechaFinP_FechaRegistroF.setVisible(false);

            labelDescuentoP.setVisible(false);
            labelCostoP.setVisible(false);
            txtDescuentoP.setVisible(false);
            txtCostoP.setVisible(false);
            
            jPanel2.setVisible(false);
            
            this.ICE.cargarDatosConsultaEspectaculo(listEspectaculos.getSelectedValue(), txtNombreArtista, txtNombreEspectaculo, txtDuracion, txtCantEspectadoresMinima, txtCantEspectadoresMaxima, txtURL, txtCosto, txtFechaRegistro, txtDescripcion);
            this.ICE.obtenerListaFunciones(listFunciones);
            String espectNombre = listEspectaculos.getSelectedValue();
            this.ICP.obtenerPaqueteEspectaculo(listPaquetes, listEspectaculos.getSelectedValue());
        }
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Dimension desktopSize = jDesktopPane2.getSize();
        Dimension jInternalFrameSize = jFrame1.getSize();
        jFrame1.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
        (desktopSize.height- jInternalFrameSize.height)/2);
        jFrame1.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextField1.setText(listPlataformas.getSelectedValue());
        this.ICE.obtenerEspectaculosPorPlataforma(listEspectaculos, jTextField1.getText());
        jFrame1.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    public void setLabelsTxtNotVisible(){
        labelNombreFP.setVisible(false);
        labelDescripcionP_FechaF.setVisible(false);
        labelFechaInicioP_HoraInicioF.setVisible(false);
        labelFechaFinP_FechaRegistroF.setVisible(false);
        labelDescuentoP.setVisible(false);
        labelCostoP.setVisible(false);
        txtNombreFP.setVisible(false);
        txtDescripcionP_FechaF.setVisible(false);
        txtFechaInicioP_HoraInicioF.setVisible(false);
        txtFechaFinP_FechaRegistroF.setVisible(false);
        txtDescuentoP.setVisible(false);
        txtCostoP.setVisible(false);
        jPanel2.setVisible(false);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFuncion;
    private javax.swing.JButton btnFuncion1;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelCostoP;
    private javax.swing.JLabel labelDescripcionP_FechaF;
    private javax.swing.JLabel labelDescuentoP;
    private javax.swing.JLabel labelFechaFinP_FechaRegistroF;
    private javax.swing.JLabel labelFechaInicioP_HoraInicioF;
    private javax.swing.JLabel labelNombreFP;
    private javax.swing.JLabel labelPaqueteEspectaculos;
    private javax.swing.JList<String> listEspectaculos;
    private javax.swing.JList<String> listEspectaculosDePaquete;
    private javax.swing.JList<String> listFunciones;
    private javax.swing.JList<String> listPaquetes;
    private javax.swing.JList<String> listPlataformas;
    private javax.swing.JLabel txtCantEspectadoresMaxima;
    private javax.swing.JLabel txtCantEspectadoresMinima;
    private javax.swing.JLabel txtCosto;
    private javax.swing.JLabel txtCostoP;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JLabel txtDescripcionP_FechaF;
    private javax.swing.JLabel txtDescuentoP;
    private javax.swing.JLabel txtDuracion;
    private javax.swing.JLabel txtFechaFinP_FechaRegistroF;
    private javax.swing.JLabel txtFechaInicioP_HoraInicioF;
    private javax.swing.JLabel txtFechaRegistro;
    public static javax.swing.JLabel txtNombreArtista;
    public static javax.swing.JLabel txtNombreEspectaculo;
    private javax.swing.JLabel txtNombreFP;
    private javax.swing.JLabel txtURL;
    // End of variables declaration//GEN-END:variables
}
